const quotes = {
  happy: [
    "Smile like nothing's wrong. It probably is.",
    "Be positive. Reality hates confidence.",
    "Believe in yourself. Evidence is optional.",
    "Good vibes fix everything. Especially nothing.",
    "If it feels wrong, call it growth.",
    "Happiness is denial with better lighting.",
    "You're doing great. Don't investigate.",
    "Confidence first. Consequences later.",
    "Chase your dreams. Trip loudly.",
    "Everything's fine. Say it again.",
    "Keep shining. Ignore the smoke.",
    "Manifest it. Then panic.",
  ],
  sad: [
    "It's okay to rest. Nothing urgent stays important.",
    "You tried. That counts for something vague.",
    "Lower your expectations. Lower.",
    "Take your time. The deadline will pass without you.",
    "Not every day needs progress. Some need naps.",
    "It's fine to feel lost. Maps are overrated.",
    "Tomorrow is another day. Allegedly.",
    "You don't have to win. You can simply stop.",
    "Crying is emotional maintenance.",
    "Hope is on backorder.",
    "The bar is on the floor. Walk over it.",
    "Let the rain handle the mood board.",
  ],
  angry: [
    "Prove them wrong. Out of pure spite.",
    "Work harder. Make it personal.",
    "Win aggressively. Ask questions never.",
    "Use your rage productively. Or loudly.",
    "They doubted you. Be inconvenient.",
    "Grind like it owes you money.",
    "Dominate your goals. Intimidate your calendar.",
    "Succeed so hard it gets awkward.",
    "Failure is unacceptable. Screaming is optional.",
    "Channel chaos. Deliver results.",
    "Burn out the doubt.",
    "Turn fury into follow-through.",
  ],
  chill: [
    "Breathe in. Breathe out. Ignore everything.",
    "Go with the flow. Preferably away from responsibility.",
    "Relax. Nothing needs immediate effort.",
    "Peace comes from not caring that much.",
    "You'll get to it when it becomes a problem.",
    "Do less. Feel superior.",
    "Stay calm. Let tomorrow panic.",
    "Vibes first. Tasks later.",
    "It's fine to wait. Time loves that.",
    "Zen is just apathy in comfy clothes.",
    "Stretch your goals into next week.",
    "Snooze the universe.",
  ],
};
